### ISSUE TITLE
Scooby's todo list

### ISSUE THREAD

**Issue by ScoobySharky** [accessibilitywars/zaw2#78]
**Comment to request for any builds/guides or to push forwards any planned task.**

## New Builds

To Launch:
- [x] pQHerald (17/05)
- [x] cWB (26/05)
- [x] cAMech (26/05)
- [x] pAMech (26/05)

To Create:
- [ ] hFB (31/05)
- [x] cWB (24/05)
- [x] cAMech (24/05)
- [x] pAMech (24/05)

To Test:
- [x] cWB (20/05)
- [x] pWB (20/05) (might need to revisit, doesn't seem realistic right now)
- [x] pAMech (24/05)
- [ ] cATempest (Wizicist build) (24/05)
- [x] cAMech (19/05)
- [ ] cDD (roundtuit)

To Revisit/Improve
- [ ] cRen (roundtuit)
- [ ] pBers/some sort of Warrior (might drop this due to low personal interest in warrior)

## Existing Builds

- [ ] Add all skill short codes (07/06)
- [ ] Add recommended bosses (14/06) (I don't think I want to add not recommended since we did that before with Snow Crows and it created some toxicity in the community)
- [ ] Add advanced strats section for builds (i.e alternate utility etc) (14/06)
- [x] New Virtuoso rotation (26/05)

## Guides

- [ ] Magnifier Tool (14/06)
- [ ] SFTA Golem (21/06)
- [ ] Boons (roundtuit)
- [ ] Conditions (roundtuit)
- [ ] Combo FIelds (roundtuit)

**Comment by ScoobySharky** [comment]
Scooby can't commit to a todo list D:
